@extends('layouts.app', ['title' => $invoice->document_number.' · '.config('supersoft.product_name')])

@section('body')
<div class="app-shell">
    @include('partials.sidebar')
    <main class="main">
        <header class="page-header"><div><p class="eyebrow">Supplier Invoice</p><h1>{{ $invoice->document_number }}</h1><p>{{ $invoice->supplier_name }} · Invoice {{ $invoice->supplier_invoice_number }}</p></div><div style="display:flex;gap:8px"><a class="button secondary" href="{{ route('accounting.payables.print', $invoice->id) }}" target="_blank">Print</a>@if($invoice->status === 'draft' && auth()->user()->hasPermission('accounting.post'))<form method="POST" action="{{ route('accounting.payables.post', $invoice->id) }}">@csrf<button class="button primary">Post Supplier Invoice</button></form>@endif</div></header>
        @if(session('status'))<div class="notice">{{ session('status') }}</div>@endif
        @if($errors->any())<div class="error">{{ $errors->first() }}</div>@endif

        <section class="card" style="margin-bottom:18px">
            <div class="detail-grid"><div class="detail-box"><span class="muted">Status</span><div class="value">{{ str($invoice->status)->replace('_', ' ')->title() }}</div></div><div class="detail-box"><span class="muted">Invoice / Due</span><div class="value">{{ $invoice->invoice_date }} / {{ $invoice->due_date }}</div></div><div class="detail-box"><span class="muted">Total</span><div class="value">Rp {{ number_format($invoice->total_amount, 0, ',', '.') }}</div></div><div class="detail-box"><span class="muted">Outstanding</span><div class="value">Rp {{ number_format($invoice->outstanding_amount, 0, ',', '.') }}</div></div></div>
            @if($invoice->journal_entry_id)<p style="margin-top:18px">Posted Journal: <a class="link-action" href="{{ route('accounting.show', $invoice->journal_entry_id) }}">{{ $invoice->journal_number }}</a></p>@endif
            <div class="table-wrap" style="margin-top:18px"><table><thead><tr><th>Account</th><th>Department</th><th>Description</th><th>Quantity</th><th>Unit Price</th><th>Amount</th></tr></thead><tbody>@foreach($lines as $line)<tr><td>{{ $line->account_code }} · {{ $line->account_name }}</td><td>{{ $line->department_name ?: '-' }}</td><td>{{ $line->description }}</td><td>{{ number_format($line->quantity, 4, ',', '.') }}</td><td>Rp {{ number_format($line->unit_price, 2, ',', '.') }}</td><td>Rp {{ number_format($line->amount, 2, ',', '.') }}</td></tr>@endforeach<tr><th colspan="5">Subtotal</th><th>Rp {{ number_format($invoice->subtotal, 2, ',', '.') }}</th></tr><tr><th colspan="5">Tax</th><th>Rp {{ number_format($invoice->tax_amount, 2, ',', '.') }}</th></tr><tr><th colspan="5">Total</th><th>Rp {{ number_format($invoice->total_amount, 2, ',', '.') }}</th></tr></tbody></table></div>
        </section>

        @if(in_array($invoice->status, ['posted', 'partially_paid'], true) && auth()->user()->hasPermission('accounting.post'))
            <section class="card" style="margin-bottom:18px"><h2>Post Supplier Payment</h2><p class="muted">Partial payment diperbolehkan. SaS otomatis mendebit Accounts Payable dan mengkredit Cash/Bank.</p><form method="POST" action="{{ route('accounting.payments.store') }}">@csrf<input type="hidden" name="invoice_id" value="{{ $invoice->id }}"><div class="form-grid"><label class="field"><span class="label">Payment Date</span><input class="input" type="date" name="payment_date" value="{{ today()->toDateString() }}" required></label><label class="field"><span class="label">Cash / Bank Account</span><select class="input" name="cash_account_id" required>@foreach($cashAccounts as $account)<option value="{{ $account->id }}">{{ $account->code }} · {{ $account->name }}</option>@endforeach</select></label><label class="field"><span class="label">Amount</span><input class="input" type="number" name="amount" min="0.01" max="{{ $invoice->outstanding_amount }}" step="0.01" value="{{ $invoice->outstanding_amount }}" required></label><label class="field"><span class="label">Payment Reference</span><input class="input" name="payment_reference" maxlength="120"></label><label class="field full"><span class="label">Notes</span><textarea class="input" name="notes" maxlength="2000"></textarea></label></div><button class="button inline" type="submit">Allocate & Post Payment</button></form></section>
        @endif

        <section class="card"><h2>Payment History</h2><div class="table-wrap"><table><thead><tr><th>Payment</th><th>Date</th><th>Reference</th><th>Allocated</th><th>Journal / Control</th></tr></thead><tbody>@forelse($payments as $payment)<tr><td>{{ $payment->document_number }}<br><span class="badge">{{ str($payment->status)->title() }}</span></td><td>{{ $payment->payment_date }}</td><td>{{ $payment->payment_reference ?: '-' }}</td><td>Rp {{ number_format($payment->allocated_amount, 2, ',', '.') }}</td><td><a class="link-action" href="{{ route('accounting.show', $payment->journal_entry_id) }}">View Journal</a>@if($payment->status === 'posted' && auth()->user()->hasPermission('accounting.post'))<form method="POST" action="{{ route('accounting.payments.reverse', $payment->id) }}" style="margin-top:8px">@csrf<input class="input" type="date" name="reversal_date" value="{{ today()->toDateString() }}" required><input class="input" name="reason" minlength="10" maxlength="500" placeholder="Mandatory reversal reason" required style="margin-top:6px"><button class="button secondary inline" style="margin-top:6px">Reverse Payment</button></form>@elseif($payment->reversal_journal_entry_id)<br><a class="link-action" href="{{ route('accounting.show', $payment->reversal_journal_entry_id) }}">Reversal Journal</a>@endif</td></tr>@empty<tr><td colspan="5">Belum ada pembayaran.</td></tr>@endforelse</tbody></table></div></section>
    </main>
</div>
@endsection
