<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8"><title>Bank Reconciliation {{ $reconciliation->statement_date }}</title>
    @vite(['resources/css/app.css'])
    <style>@page{size:A4 landscape;margin:12mm}body{background:#fff;color:#172033}.sheet{max-width:275mm;margin:auto}.head{display:flex;justify-content:space-between;border-bottom:2px solid #172033;padding-bottom:12px}.title{text-align:right}.title h1{font-size:23px;margin:0}.meta{display:grid;grid-template-columns:1.2fr 1fr 1fr;gap:12px;margin:16px 0}.box{border:1px solid #d9dee8;padding:10px}.value{font-size:17px;font-weight:600}.table{width:100%;border-collapse:collapse}.table th,.table td{border:1px solid #d9dee8;padding:6px;font-size:9px}.table th{background:#f3f5f8}.number{text-align:right}.signatures{display:grid;grid-template-columns:repeat(3,1fr);gap:30px;margin-top:38px;text-align:center}.signature{border-top:1px solid #64748b;margin-top:42px;padding-top:5px}@media print{.no-print{display:none}}</style>
</head>
<body><main class="sheet">
    <header class="head"><div><strong>{{ $company->legal_name ?: $company->name }}</strong><div>{{ $company->address }}</div><div>{{ $company->phone }} {{ $company->email }}</div></div><div class="title"><h1>BANK RECONCILIATION</h1><strong>{{ $reconciliation->bank_name }} · {{ $reconciliation->bank_account_name }}</strong><div>{{ $reconciliation->period_start }} — {{ $reconciliation->period_end }}</div><div>{{ str($reconciliation->status)->upper() }}</div></div></header>
    <section class="meta"><div class="box"><strong>Account</strong><div>{{ $reconciliation->account_number_masked ?: '-' }}</div><div>{{ $reconciliation->gl_code }} · {{ $reconciliation->gl_name }}</div><div>Source: {{ $reconciliation->original_filename }}</div></div><div class="box"><strong>Statement Balance</strong><div class="value">{{ $reconciliation->currency }} {{ number_format($reconciliation->statement_balance, 2, ',', '.') }}</div><div>Book Balance: {{ number_format($reconciliation->book_balance, 2, ',', '.') }}</div></div><div class="box"><strong>Difference</strong><div class="value">{{ $reconciliation->currency }} {{ number_format($reconciliation->difference, 2, ',', '.') }}</div><div>{{ $reconciliation->line_count }} statement lines</div></div></section>
    <table class="table"><thead><tr><th>#</th><th>Date</th><th>Reference</th><th>Description</th><th>Amount</th><th>Running Balance</th><th>Status</th><th>Journal / Resolution</th></tr></thead><tbody>@foreach($lines as $line)<tr><td>{{ $loop->iteration }}</td><td>{{ $line->transaction_date }}</td><td>{{ $line->reference ?: '-' }}</td><td>{{ $line->description }}</td><td class="number">{{ number_format($line->amount, 2, ',', '.') }}</td><td class="number">{{ $line->running_balance === null ? '-' : number_format($line->running_balance, 2, ',', '.') }}</td><td>{{ str($line->status)->title() }}</td><td>{{ $line->journal_number ?: $line->resolution_note ?: '-' }}</td></tr>@endforeach</tbody></table>
    <section class="signatures"><div><div class="signature">Prepared By</div></div><div><div class="signature">Reviewed By</div></div><div><div class="signature">Approved By{{ $reconciliation->completed_by_name ? ': '.$reconciliation->completed_by_name : '' }}</div></div></section>
    <footer style="margin-top:24px;font-size:9px;color:#64748b">SuperSoft Enterprise · SaS · Generated {{ now()->format('d M Y H:i') }}</footer>
</main><script>window.print()</script></body></html>
