@extends('layouts.app', ['title' => $catalog->name.' · SAMS'])

@section('body')
<div class="app-shell">@include('partials.sidebar')<main class="main">
    <header class="topbar"><div><p class="eyebrow">{{ $catalog->supplier_name }}</p><h1>{{ $catalog->name }}</h1><p class="muted">{{ $catalog->original_filename }} · {{ $catalog->row_count }} rows · {{ strtoupper($catalog->currency) }}</p></div><div style="display:flex;gap:8px;"><a class="button secondary inline" href="{{ route('supplier-catalogs.index') }}">Kembali</a>@if($catalog->status==='scanned'&&auth()->user()->hasPermission('procurement.po.manage'))<form method="POST" action="{{ route('supplier-catalogs.publish',$catalog->id) }}">@csrf<button class="button primary inline" type="submit">Publish Semua Baris Valid</button></form>@endif</div></header>
    @if(session('status'))<div class="notice">{{ session('status') }}</div>@endif @if($errors->any())<div class="error">{{ $errors->first() }}</div>@endif
    @if($catalog->status==='failed')<section class="card"><h2>Scan gagal</h2><p>{{ $catalog->error_message }}</p></section>@else
    <section class="card"><div class="table-wrap"><table><thead><tr><th>Row</th><th>SKU / Produk</th><th>Harga Pack</th><th>Normalisasi</th><th>MOQ</th><th>Confidence</th><th>Status</th></tr></thead><tbody>
    @foreach($items as $item)<tr><td>{{ $item->source_row }}</td><td>
        @if(auth()->user()->hasPermission('procurement.po.manage'))<form id="catalog-item-{{ $item->id }}" method="POST" action="{{ route('supplier-catalogs.items.update',[$catalog->id,$item->id]) }}" style="display:grid;gap:6px;min-width:240px;">@csrf @method('PUT')<input class="input" name="source_sku" value="{{ $item->source_sku }}" placeholder="SKU"><input class="input" name="source_name" value="{{ $item->source_name }}" required></form>@else<strong>{{ $item->source_name }}</strong><br>{{ $item->source_sku }}@endif
    </td><td>@if(auth()->user()->hasPermission('procurement.po.manage'))<input class="input" form="catalog-item-{{ $item->id }}" type="number" step="0.0001" name="price" value="{{ $item->price }}" required>@else Rp {{ number_format($item->price,0,',','.') }} / {{ $item->pack_quantity }} {{ $item->pack_unit }} @endif</td><td>@if(auth()->user()->hasPermission('procurement.po.manage'))<div style="display:flex;gap:5px;"><input class="input" form="catalog-item-{{ $item->id }}" type="number" step="0.000001" name="normalized_quantity" value="{{ $item->normalized_quantity }}" required><input class="input" form="catalog-item-{{ $item->id }}" name="normalized_unit" value="{{ $item->normalized_unit }}" required></div>@else Rp {{ number_format($item->normalized_unit_price,0,',','.') }} / {{ $item->normalized_unit }} @endif</td><td>@if(auth()->user()->hasPermission('procurement.po.manage'))<input class="input" form="catalog-item-{{ $item->id }}" type="number" step="0.0001" name="minimum_order_quantity" value="{{ $item->minimum_order_quantity }}" required>@else{{ $item->minimum_order_quantity }}@endif</td><td>{{ number_format($item->confidence*100,0) }}%</td><td><span class="status">{{ $item->status }}</span>@if(auth()->user()->hasPermission('procurement.po.manage'))<button class="link-action" form="catalog-item-{{ $item->id }}" type="submit" style="margin-top:6px;">Simpan</button>@endif</td></tr>@endforeach
    </tbody></table></div>{{ $items->links() }}</section>@endif
</main></div>
@endsection
