@extends('layouts.app')

@section('title', 'SHRiS · Human Resources')

@section('body')
<div class="app-shell">
    @include('partials.sidebar')
    <main class="main">
        <header class="page-header">
            <div><p class="eyebrow">SHRiS · {{ $company->name }}</p><h1>Human Resources</h1><p>Employee lifecycle, leave, and protected workforce records in one workspace.</p></div>
            <form method="GET" style="display:flex;gap:8px;align-items:center"><input class="input" name="search" value="{{ request('search') }}" placeholder="Search employee"><select class="input" name="status" onchange="this.form.submit()"><option value="">All status</option>@foreach(['active','on_leave','suspended','terminated'] as $status)<option value="{{ $status }}" @selected(request('status')===$status)>{{ str($status)->replace('_',' ')->title() }}</option>@endforeach</select><button class="button secondary inline">Search</button></form>
        </header>

        @if(session('status'))<div class="notice">{{ session('status') }}</div>@endif
        @if($errors->any())<div class="error">{{ $errors->first() }}</div>@endif

        <section class="grid stats">
            <article class="card metric-card"><p class="eyebrow">Active workforce</p><p class="stat-value">{{ $metrics['active'] }}</p><p class="muted">Employees currently active</p></article>
            <article class="card metric-card warning"><p class="eyebrow">Contracts due</p><p class="stat-value">{{ $metrics['contracts_due'] }}</p><p class="muted">Within the next 60 days</p></article>
            <article class="card metric-card"><p class="eyebrow">Pending leave</p><p class="stat-value">{{ $metrics['leave_pending'] }}</p><p class="muted">Awaiting a decision</p></article>
            <article class="card metric-card"><p class="eyebrow">On leave today</p><p class="stat-value">{{ $metrics['on_leave'] }}</p><p class="muted">Approved leave in progress</p></article>
        </section>

        @if(auth()->user()->hasPermission('hris.manage'))
        <section class="grid two-columns" style="margin-top:18px">
            <article class="card"><p class="eyebrow">Organization setup</p><h2>New position</h2><form method="POST" action="{{ route('hris.positions.store') }}">@csrf<div class="form-grid"><label class="field"><span class="label">Code</span><input class="input" name="code" required maxlength="30"></label><label class="field"><span class="label">Title</span><input class="input" name="title" required></label><label class="field"><span class="label">Department</span><select class="input" name="department_id"><option value="">Company-wide</option>@foreach($departments as $department)<option value="{{ $department->id }}">{{ $department->name }}</option>@endforeach</select></label><label class="field"><span class="label">Grade</span><input class="input" name="grade" maxlength="30"></label></div><button class="button primary">Save position</button></form></article>
            <article class="card"><p class="eyebrow">Leave policy</p><h2>New leave type</h2><form method="POST" action="{{ route('hris.leave-types.store') }}">@csrf<div class="form-grid"><label class="field"><span class="label">Code</span><input class="input" name="code" required maxlength="30"></label><label class="field"><span class="label">Name</span><input class="input" name="name" required></label><label class="field"><span class="label">Annual entitlement</span><input class="input" type="number" step="0.5" min="0" max="366" name="annual_entitlement_days" required></label><div class="field"><span class="label">Controls</span><label><input type="checkbox" name="is_paid" value="1" checked> Paid leave</label><label><input type="checkbox" name="requires_attachment" value="1"> Attachment required</label></div></div><button class="button primary">Save leave type</button></form></article>
        </section>

        <section class="card" style="margin-top:18px"><p class="eyebrow">Employee onboarding</p><h2>Create employee record</h2><form method="POST" action="{{ route('hris.employees.store') }}">@csrf<div class="form-grid">
            <label class="field"><span class="label">Employee number</span><input class="input" name="employee_number" required></label><label class="field"><span class="label">Linked user</span><select class="input" name="user_id"><option value="">No login access</option>@foreach($users as $member)<option value="{{ $member->id }}">{{ $member->name }} · {{ $member->email }}</option>@endforeach</select></label>
            <label class="field"><span class="label">First name</span><input class="input" name="first_name" required></label><label class="field"><span class="label">Last name</span><input class="input" name="last_name"></label>
            <label class="field"><span class="label">Branch</span><select class="input" name="branch_id" required><option value="">Select branch</option>@foreach($branches as $branch)<option value="{{ $branch->id }}">{{ $branch->name }}</option>@endforeach</select></label><label class="field"><span class="label">Department</span><select class="input" name="department_id"><option value="">Select department</option>@foreach($departments as $department)<option value="{{ $department->id }}">{{ $department->name }}</option>@endforeach</select></label>
            <label class="field"><span class="label">Position</span><select class="input" name="position_id"><option value="">Select position</option>@foreach($positions as $position)<option value="{{ $position->id }}">{{ $position->code }} · {{ $position->title }}</option>@endforeach</select></label><label class="field"><span class="label">Manager</span><select class="input" name="manager_id"><option value="">No manager</option>@foreach($activeEmployees as $person)<option value="{{ $person->id }}">{{ $person->employee_number }} · {{ $person->first_name }} {{ $person->last_name }}</option>@endforeach</select></label>
            <label class="field"><span class="label">Employment type</span><select class="input" name="employment_type" required>@foreach(['permanent','contract','casual','intern'] as $type)<option value="{{ $type }}">{{ str($type)->title() }}</option>@endforeach</select></label><label class="field"><span class="label">Hire date</span><input class="input" type="date" name="hire_date" required></label>
            <label class="field"><span class="label">Work email</span><input class="input" type="email" name="work_email"></label><label class="field"><span class="label">Phone</span><input class="input" name="phone"></label>
        </div><button class="button primary">Create employee</button></form></section>
        @endif

        @if(auth()->user()->hasPermission('hris.leave.self') && ($myEmployee || auth()->user()->hasPermission('hris.manage')))
        <section class="card" style="margin-top:18px"><p class="eyebrow">Time off</p><h2>Submit leave request</h2><form method="POST" action="{{ route('hris.leave-requests.store') }}">@csrf<div class="form-grid">@if(auth()->user()->hasPermission('hris.manage'))<label class="field"><span class="label">Employee</span><select class="input" name="employee_id" required>@foreach($activeEmployees as $person)<option value="{{ $person->id }}">{{ $person->employee_number }} · {{ $person->first_name }} {{ $person->last_name }}</option>@endforeach</select></label>@endif<label class="field"><span class="label">Leave type</span><select class="input" name="leave_type_id" required>@foreach($leaveTypes->where('is_active', true) as $type)<option value="{{ $type->id }}">{{ $type->name }}</option>@endforeach</select></label><label class="field"><span class="label">Starts</span><input class="input" type="date" name="starts_on" required></label><label class="field"><span class="label">Ends</span><input class="input" type="date" name="ends_on" required></label><label class="field full"><span class="label">Reason</span><textarea class="input" name="reason" rows="2" required></textarea></label></div><button class="button primary">Submit request</button></form></section>
        @endif

        <section class="card" style="margin-top:18px"><div class="section-heading"><div><p class="eyebrow">Workforce directory</p><h2>Employees</h2></div></div><div class="table-wrap"><table><thead><tr><th>Employee</th><th>Organization</th><th>Employment</th><th>Status</th><th></th></tr></thead><tbody>@forelse($employees as $employee)<tr><td><strong>{{ $employee->employee_number }}</strong><br>{{ $employee->first_name }} {{ $employee->last_name }}</td><td>{{ $employee->position_title ?: '—' }}<br><span class="muted">{{ $employee->department_name ?: $employee->branch_name }}</span></td><td>{{ str($employee->employment_type)->title() }}<br><span class="muted">Since {{ \Carbon\Carbon::parse($employee->hire_date)->format('d M Y') }}</span></td><td><span class="status">{{ str($employee->status)->replace('_',' ')->title() }}</span></td><td><a class="button secondary inline" href="{{ route('hris.employees.show', $employee->id) }}">Open</a></td></tr>@empty<tr><td colspan="5"><div class="empty-state">No employee records yet.</div></td></tr>@endforelse</tbody></table></div>{{ $employees->links() }}</section>

        <section class="card" style="margin-top:18px"><p class="eyebrow">Leave control</p><h2>Recent requests</h2><div class="table-wrap"><table><thead><tr><th>Employee</th><th>Leave</th><th>Period</th><th>Status</th><th>Action</th></tr></thead><tbody>@forelse($leaveRequests as $requestRow)<tr><td>{{ $requestRow->employee_number }}<br><span class="muted">{{ $requestRow->first_name }} {{ $requestRow->last_name }}</span></td><td>{{ $requestRow->leave_type_name }}<br><span class="muted">{{ number_format($requestRow->requested_days, 1) }} workdays</span></td><td>{{ \Carbon\Carbon::parse($requestRow->starts_on)->format('d M') }} – {{ \Carbon\Carbon::parse($requestRow->ends_on)->format('d M Y') }}</td><td><span class="status">{{ str($requestRow->status)->title() }}</span></td><td>@if($requestRow->status==='submitted' && auth()->user()->hasPermission('hris.leave.approve'))<div style="display:flex;gap:6px"><form method="POST" action="{{ route('hris.leave-requests.decision',$requestRow->id) }}">@csrf<input type="hidden" name="decision" value="approved"><button class="button primary inline">Approve</button></form><form method="POST" action="{{ route('hris.leave-requests.decision',$requestRow->id) }}">@csrf<input type="hidden" name="decision" value="rejected"><button class="button secondary inline">Reject</button></form></div>@else—@endif</td></tr>@empty<tr><td colspan="5"><div class="empty-state">No leave requests yet.</div></td></tr>@endforelse</tbody></table></div></section>
    </main>
</div>
@endsection
