@extends('layouts.app')

@section('title', $employee->first_name.' '.$employee->last_name)

@section('body')
<div class="app-shell">@include('partials.sidebar')<main class="main">
    <header class="page-header"><div><p class="eyebrow">{{ $employee->employee_number }} · SHRiS</p><h1>{{ $employee->first_name }} {{ $employee->last_name }}</h1><p>{{ $employee->position_title ?: 'Position not assigned' }} · {{ $employee->department_name ?: $employee->branch_name }}</p></div><a class="button secondary" href="{{ route('hris.index') }}">Back to HR</a></header>
    @if(session('status'))<div class="notice">{{ session('status') }}</div>@endif @if($errors->any())<div class="error">{{ $errors->first() }}</div>@endif
    <section class="grid detail-grid"><article class="card"><p class="eyebrow">Status</p><h2>{{ str($employee->status)->replace('_',' ')->title() }}</h2></article><article class="card"><p class="eyebrow">Employment</p><h2>{{ str($employee->employment_type)->title() }}</h2><p class="muted">Hired {{ \Carbon\Carbon::parse($employee->hire_date)->format('d M Y') }}</p></article><article class="card"><p class="eyebrow">Manager</p><h2>{{ trim(($employee->manager_first_name ?? '').' '.($employee->manager_last_name ?? '')) ?: 'Not assigned' }}</h2></article><article class="card"><p class="eyebrow">Contract end</p><h2>{{ $employee->contract_end_date ? \Carbon\Carbon::parse($employee->contract_end_date)->format('d M Y') : 'Open-ended' }}</h2></article></section>

    <section class="grid two-columns" style="margin-top:18px"><article class="card"><p class="eyebrow">Contact</p><h2>Employee details</h2><dl class="detail-list"><div><dt>Work email</dt><dd>{{ $employee->work_email ?: '—' }}</dd></div><div><dt>Phone</dt><dd>{{ $employee->phone ?: '—' }}</dd></div>@if($canSensitive)<div><dt>Personal email</dt><dd>{{ $employee->personal_email ?: '—' }}</dd></div><div><dt>National ID</dt><dd>{{ $employee->national_id_last4 ? '•••• •••• •••• '.$employee->national_id_last4 : '—' }}</dd></div><div><dt>Date of birth</dt><dd>{{ $employee->birth_date ? \Carbon\Carbon::parse($employee->birth_date)->format('d M Y') : '—' }}</dd></div>@endif</dl></article>
    @if(auth()->user()->hasPermission('hris.manage'))<article class="card"><p class="eyebrow">Lifecycle control</p><h2>Update employment</h2><form method="POST" action="{{ route('hris.employees.update',$employee->id) }}">@csrf @method('PATCH')<label class="field"><span class="label">Status</span><select class="input" name="status">@foreach(['active','on_leave','suspended','terminated'] as $status)<option value="{{ $status }}" @selected($employee->status===$status)>{{ str($status)->replace('_',' ')->title() }}</option>@endforeach</select></label><label class="field"><span class="label">Contract end</span><input class="input" type="date" name="contract_end_date" value="{{ $employee->contract_end_date }}"></label><label class="field"><span class="label">Termination date</span><input class="input" type="date" name="termination_date" value="{{ $employee->termination_date }}"></label><label class="field"><span class="label">Termination reason</span><textarea class="input" name="termination_reason" rows="2">{{ $employee->termination_reason }}</textarea></label><button class="button primary">Save lifecycle</button></form></article>@endif</section>

    <section class="card" style="margin-top:18px"><p class="eyebrow">Leave ledger</p><h2>Balances</h2><div class="table-wrap"><table><thead><tr><th>Year</th><th>Leave type</th><th>Entitled</th><th>Carried</th><th>Used</th><th>Available</th></tr></thead><tbody>@forelse($balances as $balance)<tr><td>{{ $balance->year }}</td><td>{{ $balance->leave_type_name }}</td><td>{{ number_format($balance->entitled_days,1) }}</td><td>{{ number_format($balance->carried_days,1) }}</td><td>{{ number_format($balance->used_days,1) }}</td><td><strong>{{ number_format($balance->entitled_days+$balance->carried_days-$balance->used_days,1) }}</strong></td></tr>@empty<tr><td colspan="6">No balance available.</td></tr>@endforelse</tbody></table></div></section>

    @if($canSensitive)<section class="card" style="margin-top:18px"><p class="eyebrow">Protected documents</p><h2>Encrypted employee files</h2>@if(auth()->user()->hasPermission('hris.manage'))<form method="POST" enctype="multipart/form-data" action="{{ route('hris.documents.store',$employee->id) }}" style="display:flex;gap:10px;align-items:end;flex-wrap:wrap">@csrf<label class="field"><span class="label">Document type</span><select class="input" name="document_type">@foreach(['identity','contract','certificate','medical','other'] as $type)<option value="{{ $type }}">{{ str($type)->title() }}</option>@endforeach</select></label><label class="field"><span class="label">PDF or image · max 10 MB</span><input class="input" type="file" name="document" accept=".pdf,.jpg,.jpeg,.png" required></label><button class="button primary">Encrypt & upload</button></form>@endif<div class="table-wrap"><table><thead><tr><th>Type</th><th>File</th><th>Uploaded</th><th></th></tr></thead><tbody>@forelse($documents as $document)<tr><td>{{ str($document->document_type)->title() }}</td><td>{{ $document->original_name }}</td><td>{{ \Carbon\Carbon::parse($document->created_at)->format('d M Y H:i') }}</td><td><a class="button secondary inline" href="{{ route('hris.documents.download',$document->id) }}">Secure download</a></td></tr>@empty<tr><td colspan="4">No protected documents.</td></tr>@endforelse</tbody></table></div></section>@endif
</main></div>
@endsection
