@extends('layouts.app', ['title' => 'Advanced Accounting Controls · '.config('supersoft.product_name')])
@section('body')
<div class="app-shell">@include('partials.sidebar')<main class="main">
<header class="page-header"><div><p class="eyebrow">SaS · Controlled Accounting</p><h1>Credit Notes & Fiscal Close</h1><p>Dokumen koreksi dan year-end close tanpa menghapus histori ledger.</p></div></header>
@if(session('status'))<div class="notice">{{ session('status') }}</div>@endif @if($errors->any())<div class="error">{{ $errors->first() }}</div>@endif
@if(auth()->user()->hasPermission('accounting.manage'))
<div class="grid" style="grid-template-columns:repeat(auto-fit,minmax(340px,1fr));margin-bottom:18px">
<section class="card"><h2>AP Credit Note</h2><form method="POST" action="{{ route('accounting.credit-notes.store') }}">@csrf<input type="hidden" name="type" value="ap"><div class="form-grid"><label class="field full"><span class="label">Supplier Invoice</span><select class="input" name="invoice_id" required>@foreach($payableInvoices as $invoice)<option value="{{ $invoice->id }}">{{ $invoice->document_number }} · {{ $invoice->party_name }} · Outstanding {{ number_format($invoice->outstanding_amount,2,',','.') }}</option>@endforeach</select></label><label class="field"><span class="label">Date</span><input class="input" type="date" name="credit_date" value="{{ today()->toDateString() }}" required></label><label class="field"><span class="label">Amount</span><input class="input" type="number" step="0.01" min="0.01" name="amount" required></label><label class="field"><span class="label">Supplier Reference</span><input class="input" name="external_reference"></label><label class="field"><span class="label">Expense / Asset Offset</span><select class="input" name="offset_account_id">@foreach($apOffsetAccounts as $account)<option value="{{ $account->id }}">{{ $account->code }} · {{ $account->name }}</option>@endforeach</select></label><label class="field full"><span class="label">Reason</span><textarea class="input" name="reason" required></textarea></label></div><button class="button inline">Save AP Credit Note</button></form></section>
<section class="card"><h2>AR Credit Note</h2><form method="POST" action="{{ route('accounting.credit-notes.store') }}">@csrf<input type="hidden" name="type" value="ar"><div class="form-grid"><label class="field full"><span class="label">Customer Invoice</span><select class="input" name="invoice_id" required>@foreach($receivableInvoices as $invoice)<option value="{{ $invoice->id }}">{{ $invoice->document_number }} · {{ $invoice->party_name }} · Outstanding {{ number_format($invoice->outstanding_amount,2,',','.') }}</option>@endforeach</select></label><label class="field"><span class="label">Date</span><input class="input" type="date" name="credit_date" value="{{ today()->toDateString() }}" required></label><label class="field"><span class="label">Amount</span><input class="input" type="number" step="0.01" min="0.01" name="amount" required></label><label class="field"><span class="label">Customer Reference</span><input class="input" name="external_reference"></label><label class="field"><span class="label">Revenue Offset</span><select class="input" name="offset_account_id">@foreach($arOffsetAccounts as $account)<option value="{{ $account->id }}">{{ $account->code }} · {{ $account->name }}</option>@endforeach</select></label><label class="field full"><span class="label">Reason</span><textarea class="input" name="reason" required></textarea></label></div><button class="button inline">Save AR Credit Note</button></form></section>
</div>
@endif
<section class="card" style="margin-bottom:18px"><h2>Credit Note Register</h2><div class="table-wrap"><table><thead><tr><th>Document</th><th>Type / Date</th><th>Reference</th><th>Amount</th><th>Status</th><th>Journal</th><th></th></tr></thead><tbody>@forelse($creditNotes as $note)<tr><td>{{ $note->document_number }}</td><td>{{ strtoupper($note->type) }} · {{ $note->credit_date }}</td><td>{{ $note->external_reference ?: '-' }}<br><span class="muted">{{ $note->reason }}</span></td><td>{{ $note->currency }} {{ number_format($note->foreign_amount,2,',','.') }}<br><span class="muted">Base {{ number_format($note->amount,2,',','.') }}</span></td><td><span class="badge">{{ str($note->status)->title() }}</span></td><td>@if($note->journal_entry_id)<a class="link-action" href="{{ route('accounting.show',$note->journal_entry_id) }}">{{ $note->journal_number }}</a>@else - @endif</td><td>@if($note->status === 'draft' && auth()->user()->hasPermission('accounting.post'))<form method="POST" action="{{ route('accounting.credit-notes.post',$note->id) }}">@csrf<button class="button inline">Post</button></form>@endif</td></tr>@empty<tr><td colspan="7">Belum ada credit note.</td></tr>@endforelse</tbody></table></div></section>
<section class="card"><div class="toolbar section-heading"><div><h2>Fiscal-Year Closing</h2><p class="muted">Januari–November harus sudah ditutup. Sistem membuat closing journal dan full-year lock.</p></div></div>@if(auth()->user()->hasPermission('accounting.post'))<form method="POST" action="{{ route('accounting.fiscal-close.store') }}">@csrf<div class="form-grid"><label class="field"><span class="label">Fiscal Year</span><input class="input" type="number" min="2000" max="2100" name="fiscal_year" value="{{ now()->subYear()->year }}" required></label><label class="field"><span class="label">Retained Earnings Account</span><select class="input" name="retained_earnings_account_id" required>@foreach($equityAccounts as $account)<option value="{{ $account->id }}">{{ $account->code }} · {{ $account->name }}</option>@endforeach</select></label></div><button class="button primary inline">Close Fiscal Year</button></form>@endif<div class="table-wrap" style="margin-top:18px"><table><thead><tr><th>Year</th><th>Net Income</th><th>Retained Earnings</th><th>Status</th><th>Closed</th><th>Control</th></tr></thead><tbody>@forelse($fiscalCloses as $close)<tr><td>{{ $close->fiscal_year }}</td><td>{{ number_format($close->net_income,2,',','.') }}</td><td>{{ $close->retained_code }} · {{ $close->retained_name }}</td><td><span class="badge">{{ str($close->status)->title() }}</span></td><td>{{ $close->closed_at }}</td><td>@if($close->status === 'completed' && auth()->user()->hasPermission('accounting.post'))<form method="POST" action="{{ route('accounting.fiscal-close.reopen',$close->id) }}">@csrf<input class="input" name="reason" minlength="10" maxlength="500" placeholder="Mandatory reopen reason" required><button class="button secondary inline" style="margin-top:6px">Reopen via Reversal</button></form>@endif</td></tr>@empty<tr><td colspan="6">Belum ada fiscal-year close.</td></tr>@endforelse</tbody></table></div></section>
</main></div>
@endsection
