@extends('layouts.app', ['title' => 'Accounting Automation · SuperSoft'])
@section('body')
<div class="app-shell">@include('partials.sidebar')<main class="main">
<header class="page-header"><div><p class="eyebrow">SaS · {{ $company->name }}</p><h1>Automation & Cash Flow Setup</h1><p>Cash-flow mapping and controlled recurring journal drafts.</p></div></header>
@if(session('status'))<div class="notice">{{ session('status') }}</div>@endif @if($errors->any())<div class="error">{{ $errors->first() }}</div>@endif
<section class="card" style="margin-bottom:18px"><p class="eyebrow">Cash flow mapping</p><h2>Account classification</h2><p class="muted">Mark asset accounts representing cash or bank. Classify contra accounts for accurate operating, investing, and financing reporting.</p><div class="table-wrap"><table><thead><tr><th>Account</th><th>Type</th><th>Cash / Bank</th><th>Default activity</th><th></th></tr></thead><tbody>@foreach($accounts as $account)<tr><form method="POST" action="{{ route('accounting.automation.accounts.update',$account->id) }}">@csrf<td>{{ $account->code }} · {{ $account->name }}</td><td>{{ str($account->type)->title() }}</td><td><input type="checkbox" name="is_cash_account" value="1" @checked($account->is_cash_account) @disabled($account->type!=='asset')></td><td><select class="input" name="cash_flow_activity"><option value="">Automatic / operating</option>@foreach(['operating','investing','financing'] as $activity)<option value="{{ $activity }}" @selected($account->cash_flow_activity===$activity)>{{ str($activity)->title() }}</option>@endforeach</select></td><td><button class="button secondary inline">Save</button></td></form></tr>@endforeach</tbody></table></div></section>
<section class="card" style="margin-bottom:18px"><p class="eyebrow">Recurring journals</p><h2>New template</h2><form method="POST" action="{{ route('accounting.automation.templates.store') }}">@csrf<div class="form-grid"><label class="field"><span class="label">Template name</span><input class="input" name="name" required></label><label class="field"><span class="label">Frequency</span><select class="input" name="frequency"><option value="monthly">Monthly</option><option value="quarterly">Quarterly</option><option value="yearly">Yearly</option></select></label><label class="field"><span class="label">Start date</span><input class="input" type="date" name="starts_on" value="{{ today()->startOfMonth()->toDateString() }}" required></label><label class="field"><span class="label">End date</span><input class="input" type="date" name="ends_on"></label><label class="field"><span class="label">Cash-flow activity</span><select class="input" name="cash_flow_activity"><option value="">Non-cash / automatic</option>@foreach(['operating','investing','financing'] as $activity)<option value="{{ $activity }}">{{ str($activity)->title() }}</option>@endforeach</select></label><label class="field"><span class="label">Journal type</span><span><input type="checkbox" name="is_adjustment" value="1"> Adjustment journal</span></label><label class="field full"><span class="label">Memo</span><textarea class="input" name="memo" required></textarea></label></div><div class="table-wrap"><table><thead><tr><th>Account</th><th>Department</th><th>Description</th><th>Debit</th><th>Credit</th></tr></thead><tbody>@for($i=0;$i<6;$i++)<tr><td><select class="input" name="lines[{{$i}}][gl_account_id]"><option value="">Select account</option>@foreach($accounts as $account)<option value="{{$account->id}}">{{$account->code}} · {{$account->name}}</option>@endforeach</select></td><td><select class="input" name="lines[{{$i}}][department_id]"><option value="">—</option>@foreach($departments as $department)<option value="{{$department->id}}">{{$department->name}}</option>@endforeach</select></td><td><input class="input" name="lines[{{$i}}][description]"></td><td><input class="input" type="number" min="0" step="0.01" name="lines[{{$i}}][debit]"></td><td><input class="input" type="number" min="0" step="0.01" name="lines[{{$i}}][credit]"></td></tr>@endfor</tbody></table></div><button class="button primary" style="margin-top:16px">Save template</button></form></section>
<section class="card"><p class="eyebrow">Schedule control</p><h2>Templates</h2><div class="table-wrap"><table><thead><tr><th>Name</th><th>Frequency</th><th>Next run</th><th>Status</th><th></th></tr></thead><tbody>@forelse($templates as $template)<tr><td><strong>{{$template->name}}</strong><br><span class="muted">{{$template->memo}}</span></td><td>{{str($template->frequency)->title()}}</td><td>{{$template->next_run_on}}</td><td><span class="status">{{$template->is_active?'Active':'Completed'}}</span></td><td>@if($template->is_active)<form method="POST" action="{{route('accounting.automation.templates.generate',$template->id)}}">@csrf<input type="hidden" name="journal_date" value="{{$template->next_run_on}}"><button class="button primary inline">Generate draft</button></form>@else—@endif</td></tr>@empty<tr><td colspan="5">No recurring templates.</td></tr>@endforelse</tbody></table></div></section>
</main></div>
@endsection
