@extends('layouts.app', ['title' => 'Accounting Configuration · '.config('supersoft.product_name')])
@section('body')
<div class="app-shell">@include('partials.sidebar')<main class="main">
<header class="page-header"><div><p class="eyebrow">SaS · {{ $company->name }}</p><h1>Accounting Configuration</h1><p>Tax codes, posting defaults, dan kontrol three-way matching yang dimiliki perusahaan.</p></div></header>
@if(session('status'))<div class="notice">{{ session('status') }}</div>@endif @if($errors->any())<div class="error">{{ $errors->first() }}</div>@endif
<div class="grid" style="grid-template-columns:repeat(auto-fit,minmax(320px,1fr));margin-bottom:18px">
<section class="card"><h2>Three-Way Match Control</h2><form method="POST" action="{{ route('accounting.configuration.settings') }}">@csrf<div class="form-grid"><label class="field"><span class="label">Price tolerance %</span><input class="input" type="number" step="0.0001" min="0" max="100" name="po_price_tolerance_percent" value="{{ $settings->po_price_tolerance_percent ?? 2 }}" required></label><label class="field"><span class="label">Quantity tolerance %</span><input class="input" type="number" step="0.0001" min="0" max="100" name="po_quantity_tolerance_percent" value="{{ $settings->po_quantity_tolerance_percent ?? 0 }}" required></label></div><button class="button inline">Save Controls</button></form></section>
<section class="card"><h2>Add Tax Code</h2><form method="POST" action="{{ route('accounting.configuration.tax-codes') }}">@csrf<div class="form-grid"><label class="field"><span class="label">Code</span><input class="input" name="code" required></label><label class="field"><span class="label">Name</span><input class="input" name="name" required></label><label class="field"><span class="label">Type</span><select class="input" name="type"><option value="purchase">Purchase / Input</option><option value="sales">Sales / Output</option><option value="withholding">Withholding Payable</option></select></label><label class="field"><span class="label">Rate %</span><input class="input" type="number" step="0.0001" min="0" max="100" name="rate_percent" required></label><label class="field full"><span class="label">GL Account</span><select class="input" name="gl_account_id" required>@foreach($accounts as $account)<option value="{{ $account->id }}">{{ $account->code }} · {{ $account->name }} ({{ $account->type }})</option>@endforeach</select></label></div><button class="button inline">Add Tax Code</button></form></section>
</div>
<section class="card" style="margin-bottom:18px"><h2>Tax Code Register</h2><div class="table-wrap"><table><thead><tr><th>Code</th><th>Name</th><th>Type</th><th>Rate</th><th>GL Account</th><th>Status</th><th>Control</th></tr></thead><tbody>@forelse($taxCodes as $tax)<tr><td>{{ $tax->code }}</td><td>{{ $tax->name }}</td><td>{{ str($tax->type)->title() }}</td><td>{{ number_format($tax->rate_percent, 4, ',', '.') }}%</td><td>{{ $tax->gl_code }} · {{ $tax->gl_name }}</td><td><span class="badge">{{ $tax->is_active ? 'Active' : 'Inactive' }}</span></td><td><form method="POST" action="{{ route('accounting.configuration.tax-codes.toggle',$tax->id) }}">@csrf<button class="button secondary inline">{{ $tax->is_active ? 'Deactivate' : 'Activate' }}</button></form></td></tr>@empty<tr><td colspan="7">Belum ada tax code.</td></tr>@endforelse</tbody></table></div></section>
<section class="card"><h2>Configurable Posting Rules</h2><form method="POST" action="{{ route('accounting.configuration.posting-rules') }}">@csrf<div class="form-grid"><label class="field"><span class="label">Transaction / Role</span><select class="input" id="posting-transaction" name="transaction_type">@foreach($ruleOptions as $transaction => $roles)@foreach($roles as $role => $types)<option value="{{ $transaction }}" data-role="{{ $role }}">{{ str($transaction)->replace('_',' ')->title() }} · {{ str($role)->replace('_',' ')->title() }}</option>@endforeach @endforeach</select></label><label class="field"><span class="label">Account Role</span><input class="input" id="posting-role" name="account_role" value="payable" readonly></label><label class="field"><span class="label">GL Account</span><select class="input" name="gl_account_id">@foreach($accounts as $account)<option value="{{ $account->id }}">{{ $account->code }} · {{ $account->name }}</option>@endforeach</select></label></div><button class="button inline">Save Posting Rule</button></form><div class="table-wrap" style="margin-top:18px"><table><thead><tr><th>Transaction</th><th>Role</th><th>Default GL Account</th></tr></thead><tbody>@forelse($postingRules as $rule)<tr><td>{{ str($rule->transaction_type)->replace('_',' ')->title() }}</td><td>{{ str($rule->account_role)->replace('_',' ')->title() }}</td><td>{{ $rule->gl_code }} · {{ $rule->gl_name }}</td></tr>@empty<tr><td colspan="3">Belum ada posting rule.</td></tr>@endforelse</tbody></table></div></section>
<div class="grid two-columns" style="margin-top:18px">
<section class="card"><p class="eyebrow">Multi-currency</p><h2>Exchange Rate</h2><p class="muted">Nilai 1 unit mata uang asing dalam {{ $company->currency }}.</p><form method="POST" action="{{ route('accounting.configuration.exchange-rates') }}">@csrf<div class="form-grid"><label class="field"><span class="label">Currency</span><input class="input" name="currency" maxlength="3" placeholder="USD" required></label><label class="field"><span class="label">Rate date</span><input class="input" type="date" name="rate_date" value="{{ today()->toDateString() }}" required></label><label class="field"><span class="label">Rate to base</span><input class="input" type="number" min="0.00000001" step="0.00000001" name="rate_to_base" required></label><label class="field"><span class="label">Source</span><input class="input" name="source" value="manual"></label></div><button class="button inline">Save Exchange Rate</button></form><div class="table-wrap" style="margin-top:18px"><table><thead><tr><th>Date</th><th>Currency</th><th>Rate</th><th>Source</th></tr></thead><tbody>@forelse($exchangeRates as $rate)<tr><td>{{$rate->rate_date}}</td><td>{{$rate->currency}}</td><td>{{number_format($rate->rate_to_base,8,',','.')}}</td><td>{{$rate->source}}</td></tr>@empty<tr><td colspan="4">Belum ada exchange rate.</td></tr>@endforelse</tbody></table></div></section>
<section class="card"><p class="eyebrow">FX posting</p><h2>Gain & Loss Accounts</h2><form method="POST" action="{{ route('accounting.configuration.fx-accounts') }}">@csrf @foreach(['realized_fx_gain_account_id'=>'Realized FX Gain','realized_fx_loss_account_id'=>'Realized FX Loss','unrealized_fx_gain_account_id'=>'Unrealized FX Gain','unrealized_fx_loss_account_id'=>'Unrealized FX Loss'] as $field=>$label)<label class="field"><span class="label">{{$label}}</span><select class="input" name="{{$field}}" required><option value="">Select account</option>@foreach($accounts as $account) @if(str_contains($field,'gain') ? $account->type==='revenue' : $account->type==='expense')<option value="{{$account->id}}" @selected(($settings->{$field}??null)==$account->id)>{{$account->code}} · {{$account->name}}</option>@endif @endforeach</select></label>@endforeach<button class="button inline">Save FX Accounts</button></form></section>
</div>
<section class="card" style="margin-top:18px"><p class="eyebrow">Period end</p><h2>Foreign Currency Revaluation</h2><p class="muted">Revalue open AP and AR balances using the latest exchange rate. One immutable run is allowed per currency and date.</p><form class="form-grid" method="POST" action="{{route('accounting.configuration.fx-revaluation')}}">@csrf<label class="field"><span class="label">Currency</span><input class="input" name="currency" maxlength="3" placeholder="USD" required></label><label class="field"><span class="label">Revaluation date</span><input class="input" type="date" name="revaluation_date" value="{{today()->endOfMonth()->toDateString()}}" required></label><div class="field"><button class="button primary">Post Revaluation</button></div></form></section>
</main></div>
<script>const postingTransaction=document.getElementById('posting-transaction');const postingRole=document.getElementById('posting-role');const syncPostingRole=()=>postingRole.value=postingTransaction.options[postingTransaction.selectedIndex].dataset.role;postingTransaction.addEventListener('change',syncPostingRole);syncPostingRole();</script>
@endsection
