@extends('layouts.app',['title'=>str($report)->replace('-',' ')->title().' · SuperSoft'])
@section('body')
@if(!$print)<div class="app-shell">@include('partials.sidebar')<main class="main">@else<main style="padding:24px;max-width:1200px;margin:auto">@endif
<header class="page-header"><div><p class="eyebrow">Accounting Report · {{ $company->name }}</p><h1>{{ str($report)->replace('-',' ')->title() }}</h1><p>{{ $from }} – {{ $to }} · Posted journals only</p></div>@if(!$print)<a class="button secondary" target="_blank" href="{{ request()->fullUrlWithQuery(['print'=>1]) }}">Print Report</a>@endif</header>
@if(!$print)<section class="card" style="margin-bottom:18px"><form class="form-grid" method="GET"><label>From<input class="input" type="date" name="from" value="{{$from}}"></label><label>To<input class="input" type="date" name="to" value="{{$to}}"></label>@if($report==='general-ledger')<label>Account<select class="input" name="account_id"><option value="">All accounts</option>@foreach($accounts as $a)<option value="{{$a->id}}" @selected(request('account_id')==$a->id)>{{$a->code}} · {{$a->name}}</option>@endforeach</select></label>@endif @if($report==='department-profit-loss')<label>Department<select class="input" name="department_id"><option value="">All departments</option>@foreach($departments as $department)<option value="{{$department->id}}" @selected(request('department_id')==$department->id)>{{$department->name}}</option>@endforeach</select></label>@endif<div class="field"><button class="button primary">Apply Filter</button></div></form></section>@endif
@if($report==='general-ledger')
@forelse($groups as $group)<section class="card" style="margin-bottom:16px"><h2>{{$group['account']->code}} · {{$group['account']->name}}</h2><div class="table-wrap"><table><thead><tr><th>Date</th><th>Reference</th><th>Description</th><th>Debit</th><th>Credit</th><th>Balance</th></tr></thead><tbody><tr><td colspan="5"><strong>Opening Balance</strong></td><td>{{number_format($group['opening'],2,',','.')}}</td></tr>@foreach($group['lines'] as $line)<tr><td>{{$line->journal_date}}</td><td>{{$line->document_number}}</td><td>{{$line->description?:$line->memo}}</td><td>{{number_format($line->debit,2,',','.')}}</td><td>{{number_format($line->credit,2,',','.')}}</td><td>{{number_format($line->balance,2,',','.')}}</td></tr>@endforeach<tr><td colspan="5"><strong>Closing Balance</strong></td><td><strong>{{number_format($group['closing'],2,',','.')}}</strong></td></tr></tbody></table></div></section>@empty<section class="card">No posted movements in this period.</section>@endforelse
@elseif($report==='trial-balance')
<section class="card"><div class="table-wrap"><table><thead><tr><th>Account</th><th>Opening Debit</th><th>Opening Credit</th><th>Period Debit</th><th>Period Credit</th><th>Ending Debit</th><th>Ending Credit</th></tr></thead><tbody>@foreach($trial['rows'] as $row)<tr><td>{{$row['code']}} · {{$row['name']}}</td>@foreach(['opening_debit','opening_credit','period_debit','period_credit','ending_debit','ending_credit'] as $key)<td>{{number_format($row[$key],2,',','.')}}</td>@endforeach</tr>@endforeach<tr><th>TOTAL</th>@foreach(['opening_debit','opening_credit','period_debit','period_credit','ending_debit','ending_credit'] as $key)<th>{{number_format($trial['totals'][$key],2,',','.')}}</th>@endforeach</tr></tbody></table></div></section>
@elseif(in_array($report,['profit-loss','department-profit-loss']))
<section class="card"><h2>Revenue</h2>@foreach($statement['revenue'] as $row)<div class="detail-box" style="display:flex;justify-content:space-between;margin-bottom:6px"><span>{{$row['code']}} · {{$row['name']}}</span><strong>Rp {{number_format($row['amount'],2,',','.')}}</strong></div>@endforeach<h2 style="margin-top:22px">Expenses</h2>@foreach($statement['expense'] as $row)<div class="detail-box" style="display:flex;justify-content:space-between;margin-bottom:6px"><span>{{$row['code']}} · {{$row['name']}}</span><strong>Rp {{number_format($row['amount'],2,',','.')}}</strong></div>@endforeach<div class="detail-box" style="display:flex;justify-content:space-between;margin-top:18px;background:var(--primary-soft)"><strong>NET PROFIT / (LOSS)</strong><strong>Rp {{number_format($statement['netIncome'],2,',','.')}}</strong></div></section>
@elseif($report==='cash-flow')
<section class="card">@if(!$cashFlow['configured'])<div class="notice">Mark at least one cash/bank account in Automation & Cash Flow Setup.</div>@endif<div class="detail-box" style="display:flex;justify-content:space-between"><strong>Opening cash balance</strong><strong>Rp {{number_format($cashFlow['opening'],2,',','.')}}</strong></div>@foreach(['operating','investing','financing'] as $activity)<h2 style="margin-top:22px">{{str($activity)->title()}} activities</h2>@forelse($cashFlow['rows']->get($activity,collect()) as $row)<div class="detail-box" style="display:grid;grid-template-columns:100px 150px 1fr auto;gap:12px;margin-bottom:6px"><span>{{$row['date']}}</span><span>{{$row['reference']}}</span><span>{{$row['description']}}</span><strong>Rp {{number_format($row['amount'],2,',','.')}}</strong></div>@empty<p class="muted">No cash movement.</p>@endforelse<div class="detail-box" style="display:flex;justify-content:space-between"><strong>Net {{str($activity)->title()}}</strong><strong>Rp {{number_format($cashFlow['totals'][$activity],2,',','.')}}</strong></div>@endforeach<div class="detail-box" style="display:flex;justify-content:space-between;margin-top:20px;background:var(--primary-soft)"><strong>Closing cash balance</strong><strong>Rp {{number_format($cashFlow['closing'],2,',','.')}}</strong></div></section>
@elseif($report==='journal-register')
<section class="card"><div class="table-wrap"><table><thead><tr><th>Date</th><th>Reference</th><th>Type</th><th>Department</th><th>Account</th><th>Description</th><th>Debit</th><th>Credit</th></tr></thead><tbody>@forelse($register as $row)<tr><td>{{$row->journal_date}}</td><td>{{$row->document_number}}</td><td>{{str($row->source_type)->replace('_',' ')->title()}}</td><td>{{$row->department_name?:'—'}}</td><td>{{$row->code}} · {{$row->account_name}}</td><td>{{$row->description?:$row->memo}}</td><td>{{number_format($row->debit,2,',','.')}}</td><td>{{number_format($row->credit,2,',','.')}}</td></tr>@empty<tr><td colspan="8">No posted journal lines.</td></tr>@endforelse</tbody></table></div></section>
@else
<section class="card"><h2>Assets</h2>@foreach($statement['assets'] as $row)<div class="detail-box" style="display:flex;justify-content:space-between;margin-bottom:6px"><span>{{$row['code']}} · {{$row['name']}}</span><strong>Rp {{number_format($row['amount'],2,',','.')}}</strong></div>@endforeach<div class="detail-box"><strong>Total Assets: Rp {{number_format($statement['totalAssets'],2,',','.')}}</strong></div><h2 style="margin-top:22px">Liabilities & Equity</h2>@foreach($statement['liabilities']->concat($statement['equity']) as $row)<div class="detail-box" style="display:flex;justify-content:space-between;margin-bottom:6px"><span>{{$row['code']}} · {{$row['name']}}</span><strong>Rp {{number_format($row['amount'],2,',','.')}}</strong></div>@endforeach<div class="detail-box" style="display:flex;justify-content:space-between"><span>Current Earnings</span><strong>Rp {{number_format($statement['income'],2,',','.')}}</strong></div><div class="detail-box"><strong>Total Liabilities & Equity: Rp {{number_format($statement['totalLiabilities']+$statement['totalEquity'],2,',','.')}}</strong></div></section>
@endif
@if($print)<footer style="margin-top:24px;font-size:10px;color:#667085">SuperSoft Enterprise · SaS · {{now()->format('d M Y H:i')}} · Prepared / Checked / Approved</footer><script>window.print()</script></main>@else</main></div>@endif
@endsection
